#!/usr/bin/env python3

from setuptools import setup, Extension

setup(name="insgnss_tools",
      version="1.4",
      description="INS/GNSS/EKF Toolbox",
      author="Curtis L. Olson (U of MN Aerospace Engineering and Mechanics, Demoz Gebre, Chris Regan, Brian Taylor, Hamid M., et. al.)",
      author_email="curtolson@flightgear.org",
      url="https://github.com/NorthStarUAS",
      packages = ["insgnss_tools"],
      ext_modules=[
          Extension("insgnss_tools.structs",
                    define_macros=[("HAVE_PYBIND11", "1")],
                    include_dirs=["/usr/include/eigen3"],
                    sources=["src/nav_common/structs.cpp"],
                    depends=["src/nav_common/structs.h"]),
          Extension("insgnss_tools.ekf15",
                    sources=["src/nav_ekf15/pybind11.cpp",
                             "src/nav_ekf15/EKF_15state.cpp",
                             "src/nav_common/nav_functions.cpp"],
                    depends=["src/nav_ekf15/EKF_15state.h",
                             "src/nav_common/constants.h",
                             "src/nav_common/nav_functions.h"]),
          Extension("insgnss_tools.ekf15_mag",
                    sources=["src/nav_ekf15_mag/pybind11.cpp",
                             "src/nav_ekf15_mag/EKF_15state.cpp",
                             "src/nav_common/nav_functions.cpp",
                             "src/nav_common/coremag.c"],
                    depends=["src/nav_ekf15_mag/EKF_15state.h",
                             "src/nav_common/constants.h",
                             "src/nav_common/nav_functions.h",
                             "src/nav_common/coremag.h"]),
          Extension("insgnss_tools.openloop",
                    sources=["src/nav_openloop/pybind11.cpp",
                             "src/nav_openloop/openloop.cpp",
                             "src/nav_openloop/glocal.cpp",
                             "src/nav_common/nav_functions.cpp",
                             "src/nav_common/coremag.c"],
                    depends=["src/nav_openloop/openloop.h",
                             "src/nav_openloop/glocal.h",
                             "src/nav_common/constants.h",
                             "src/nav_common/nav_functions.h",
                             "src/nav_common/coremag.h"]),
          Extension("insgnss_tools.uNavINS",
                    include_dirs=["/usr/include/eigen3"],
                    sources=["src/UASLab_RAPTRS/pybind11.cpp",
                             "src/UASLab_RAPTRS/nav-functions.cpp",
                             "src/UASLab_RAPTRS/uNavINS.cpp"],
                    depends=["src/UASLab_RAPTRS/nav-functions.h",
                             "src/UASLab_RAPTRS/uNavINS.h"]),
          Extension("insgnss_tools.uNavINS_BFS",
                    include_dirs=["/usr/include/eigen3"],
                    sources=["src/BFS_raptrs/pybind11.cpp",
                             "src/BFS_raptrs/uNavINS.cpp"],
                    depends=["src/BFS_raptrs/uNavINS.h"]),
       ],
     )
